# Generated by Django 3.0.8 on 2020-08-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=35, unique=True, verbose_name='email')),
                ('KidName', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('parentName', models.CharField(max_length=25)),
                ('Country', models.CharField(max_length=15)),
                ('Kid_Age', models.IntegerField()),
                ('Phonenumber', models.CharField(max_length=15)),
                ('Kid_Aim', models.CharField(max_length=15)),
                ('Lapptop_availability', models.CharField(max_length=3)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of otp_sent')),
                ('Kid_Age', models.IntegerField()),
                ('KidName', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=20)),
                ('parentName', models.CharField(max_length=20)),
                ('Kid_Aim', models.CharField(max_length=20)),
                ('Lapptop_availability', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
