# Generated by Django 3.0.8 on 2020-09-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200901_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='KidName',
            new_name='kidName',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Kid_Age',
            new_name='kid_Age',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Kid_Aim',
            new_name='kid_Aim',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Lapptop_availability',
            new_name='lapptop_availability',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='phoneotp',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='phoneotp',
            old_name='KidName',
            new_name='kidName',
        ),
        migrations.RenameField(
            model_name='phoneotp',
            old_name='Kid_Aim',
            new_name='kid_Aim',
        ),
        migrations.RenameField(
            model_name='phoneotp',
            old_name='Lapptop_availability',
            new_name='lapptop_availability',
        ),
    ]
