# Generated by Django 3.0.8 on 2020-09-27 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200926_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=35, unique=True, verbose_name='email')),
                ('kidName', models.CharField(max_length=25)),
                ('parentName', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=15)),
                ('kid_Age', models.IntegerField()),
                ('phonenumber', models.CharField(max_length=15)),
                ('kid_Aim', models.CharField(max_length=15)),
                ('lapptop_availability', models.CharField(max_length=3)),
                ('StudentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=35, unique=True, verbose_name='email')),
                ('kidName', models.CharField(max_length=25)),
                ('parentName', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=15)),
                ('kid_Age', models.IntegerField()),
                ('phonenumber', models.CharField(max_length=15)),
                ('kid_Aim', models.CharField(max_length=15)),
                ('lapptop_availability', models.CharField(max_length=3)),
                ('ParentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
