# Generated by Django 3.0.8 on 2020-09-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_parent_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='category',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='kidName',
        ),
        migrations.RemoveField(
            model_name='account',
            name='kid_Age',
        ),
        migrations.RemoveField(
            model_name='account',
            name='kid_Aim',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lapptop_availability',
        ),
        migrations.RemoveField(
            model_name='account',
            name='parentName',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phonenumber',
        ),
    ]
