# Generated by Django 3.0.8 on 2020-09-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='Kid_Age',
            field=models.CharField(max_length=10),
        ),
    ]
