# Generated by Django 3.0.8 on 2020-09-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200927_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='ParentId',
            new_name='parentId',
        ),
        migrations.RenameField(
            model_name='phoneotp',
            old_name='Kid_Age',
            new_name='kid_Age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='StudentId',
            new_name='studentId',
        ),
        migrations.RemoveField(
            model_name='student',
            name='kid_Aim',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parentName',
        ),
    ]
