# Generated by Django 3.0.8 on 2020-09-27 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200927_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneotp',
            old_name='kid_Age',
            new_name='kid_age',
        ),
        migrations.RenameField(
            model_name='phoneotp',
            old_name='kidName',
            new_name='kidname',
        ),
    ]
