# Generated by Django 3.0.8 on 2020-09-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200927_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='kid_Age',
            new_name='kid_age',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='kidName',
            new_name='kidname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='kid_Age',
            new_name='kid_age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='kidName',
            new_name='kidname',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='kid_Aim',
        ),
    ]
