# Generated by Django 3.0.8 on 2020-10-09 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20200927_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date joined'),
            preserve_default=False,
        ),
    ]
