# Generated by Django 3.0.8 on 2020-10-09 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_phoneotp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 12, 30, 45, 959854, tzinfo=utc)),
        ),
    ]
