# Generated by Django 3.0.8 on 2020-10-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20201009_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
