# Generated by Django 3.0.8 on 2020-12-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20201201_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='Course_age',
            new_name='course_age',
        ),
        migrations.AddField(
            model_name='trainer',
            name='teachingCourse',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
