# Generated by Django 3.0.8 on 2020-12-01 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0061_auto_20201201_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainercourse',
            fields=[
                ('studentsid', models.CharField(max_length=10)),
                ('course_randId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('countOfStudent', models.IntegerField()),
                ('time', models.IntegerField()),
                ('coaching_courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses')),
                ('trainerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_email', models.EmailField(max_length=254)),
                ('a_mobileNumber', models.BigIntegerField()),
                ('qualification', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('teaching_Course', models.CharField(max_length=50)),
                ('courseAge_category', models.IntegerField()),
                ('trainerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
