# Generated by Django 3.0.8 on 2020-12-02 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_auto_20201202_0919'),
        ('trainer', '0002_auto_20201202_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='date_of_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='trainercourse',
            name='coaching_courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
    ]
