# Generated by Django 3.0.8 on 2020-12-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_auto_20201216_1308'),
        ('trainer', '0004_auto_20201216_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainercourse',
            name='coaching_courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
    ]
