# Generated by Django 3.0.8 on 2021-01-04 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_auto_20210104_1518'),
        ('trainer', '0011_auto_20210104_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_review',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 9, 48, 17, 659695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='class_review',
            name='textReview',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 9, 48, 17, 659695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trainercourse',
            name='coaching_courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
    ]
