# Generated by Django 3.0.8 on 2020-08-17 05:10

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('PricePerClass', models.IntegerField()),
                ('courseImg', models.ImageField(upload_to='')),
                ('From_age', models.ImageField(upload_to='')),
                ('To_age', models.ImageField(upload_to='')),
                ('Course_Aim', models.CharField(max_length=50)),
                ('Current_Demandofcourse', models.CharField(max_length=50)),
                ('Projectscount', models.ImageField(upload_to='')),
                ('Rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KidName', models.CharField(max_length=50)),
                ('parentName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Country', models.CharField(max_length=50)),
                ('Kid_Age', models.IntegerField()),
                ('Kid_Aim', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('Lapptop_availability', models.CharField(max_length=3)),
                ('last_login', models.DateField(default=datetime.datetime(2020, 8, 17, 5, 10, 11, 793637, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='helpdesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Query', models.CharField(max_length=500)),
                ('Img', models.ImageField(upload_to='pics')),
                ('MobileNumber', models.IntegerField()),
                ('Status', models.CharField(max_length=50)),
                ('CoursesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('MobileNumber', models.IntegerField()),
                ('Country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('TeachingCourse', models.CharField(max_length=50)),
                ('CourseAgecategory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=50)),
                ('Projectabout', models.CharField(max_length=200)),
                ('Demo_img', models.ImageField(upload_to='pics')),
                ('Files', models.FileField(upload_to='files')),
                ('Downloads', models.IntegerField(default=0)),
                ('Views', models.IntegerField(default=0)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
        ),
        migrations.CreateModel(
            name='solutiondesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Solution', models.CharField(max_length=500)),
                ('Status', models.CharField(max_length=50)),
                ('InstructedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('QueryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.helpdesk')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Photo', models.ImageField(upload_to='pics')),
                ('Comments', models.CharField(max_length=1000)),
                ('Rating', models.IntegerField()),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlternateEmail', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='pics')),
                ('DemoCourseRegistered', models.BooleanField()),
                ('Country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('DateOfjoin', models.DateField()),
                ('SchoolName', models.CharField(max_length=100)),
                ('Yourhobby', models.CharField(max_length=500)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank', models.CharField(max_length=50)),
                ('PaymentDate', models.DateField()),
                ('Ammount', models.IntegerField()),
                ('Transactionid', models.CharField(max_length=50)),
                ('PaymentStatus', models.CharField(max_length=50)),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('coursesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.TextField(blank=True, max_length=100)),
                ('Text', models.TextField(blank=True, max_length=1000)),
                ('Receiverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='home.customer')),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='home.customer')),
            ],
        ),
        migrations.CreateModel(
            name='INTERMEDIATE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseContent', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ClassCount', models.IntegerField()),
                ('Prerequisites', models.CharField(max_length=350)),
                ('Benifits', models.CharField(max_length=500)),
                ('coursesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='Paymentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.payment'),
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer'),
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=100)),
                ('KidFromage', models.IntegerField()),
                ('KidToage', models.IntegerField()),
                ('Coupon', models.CharField(max_length=50)),
                ('CouponstartDate', models.DateField()),
                ('CouponExpiredDate', models.DateField()),
                ('CoursesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificate', models.FileField(upload_to='files')),
                ('CoursesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BEGINNER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseContent', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ClassesCount', models.IntegerField()),
                ('Prerequisites', models.CharField(max_length=350)),
                ('Benifits', models.CharField(max_length=500)),
                ('coursesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
        migrations.CreateModel(
            name='batchtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classtype', models.CharField(max_length=50)),
                ('CoursesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ADVANCED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseContent', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ClassCount', models.IntegerField()),
                ('Prerequisites', models.CharField(max_length=350)),
                ('Benifits', models.CharField(max_length=500)),
                ('CoursesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
    ]
