# Generated by Django 3.0.8 on 2020-08-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200830_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprojects',
            name='Views',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Country',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=15),
        ),
    ]
