# Generated by Django 3.0.8 on 2020-09-01 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20200831_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='CoursesId',
        ),
        migrations.AddField(
            model_name='instructor',
            name='Experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='Qualification',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Refund_requestDate', models.DateField()),
                ('RefundDate', models.DateField()),
                ('Ammount', models.IntegerField()),
                ('Reason', models.CharField(max_length=100)),
                ('Transactionid', models.CharField(max_length=50)),
                ('PaymentStatus', models.CharField(default='pending', max_length=50)),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coursesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.courses')),
            ],
        ),
    ]
