# Generated by Django 3.0.8 on 2020-09-12 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_auto_20200901_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('teached_concepts', models.TextField()),
                ('today_left_concepts', models.TextField()),
                ('reason_for_left', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Class_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentsid', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('strength_class', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('textReview', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_start', models.DateField()),
                ('date_of_end', models.DateField()),
                ('type_of_batch', models.CharField(max_length=10)),
                ('discription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('percentage', models.CharField(default='0%', max_length=4)),
                ('trainerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentsid', models.CharField(max_length=10)),
                ('concepts_to_teach', models.TextField()),
                ('class_timing', models.TextField()),
                ('discription', models.CharField(max_length=100)),
                ('coaching_courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course_details')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_email', models.EmailField(max_length=254)),
                ('a_mobileNumber', models.BigIntegerField()),
                ('qualification', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('teaching_Course', models.CharField(max_length=50)),
                ('courseAge_category', models.IntegerField()),
                ('trainerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.RenameField(
            model_name='advanced',
            old_name='ClassCount',
            new_name='classesCount',
        ),
        migrations.RenameField(
            model_name='advanced',
            old_name='CourseContent',
            new_name='courseContent',
        ),
        migrations.RenameField(
            model_name='batchtype',
            old_name='UserId',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='beginner',
            old_name='ClassesCount',
            new_name='classesCount',
        ),
        migrations.RenameField(
            model_name='beginner',
            old_name='CourseContent',
            new_name='courseContent',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='Certificate',
            new_name='certificate',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='UserId',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='coupons',
            old_name='Coupon',
            new_name='coupon',
        ),
        migrations.RenameField(
            model_name='coupons',
            old_name='CouponExpiredDate',
            new_name='couponExpired_date',
        ),
        migrations.RenameField(
            model_name='coupons',
            old_name='CouponstartDate',
            new_name='couponstart_date',
        ),
        migrations.RenameField(
            model_name='coupons',
            old_name='CourseName',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='coupons',
            old_name='KidFromage',
            new_name='kid_fromage',
        ),
        migrations.RenameField(
            model_name='coupons',
            old_name='KidToage',
            new_name='kid_toage',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='Course_Aim',
            new_name='courseName',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='From_age',
            new_name='from_age',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='PricePerClass',
            new_name='pricePerClass',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='Projectscount',
            new_name='projectscount',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='To_age',
            new_name='to_age',
        ),
        migrations.RenameField(
            model_name='helpdesk',
            old_name='Img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='helpdesk',
            old_name='MobileNumber',
            new_name='mobile_Number',
        ),
        migrations.RenameField(
            model_name='helpdesk',
            old_name='Query',
            new_name='query',
        ),
        migrations.RenameField(
            model_name='helpdesk',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='helpdesk',
            old_name='UserId',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='intermediate',
            old_name='ClassCount',
            new_name='classesCount',
        ),
        migrations.RenameField(
            model_name='intermediate',
            old_name='CourseContent',
            new_name='courseContent',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Ammount',
            new_name='ammount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='PaymentDate',
            new_name='paymentDate',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='PaymentStatus',
            new_name='paymentStatus',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Transactionid',
            new_name='transactionid',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Userid',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='AlternateEmail',
            new_name='alternateEmail',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='DateOfjoin',
            new_name='dateOfjoin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='DemoCourseRegistered',
            new_name='demoCourseRegistered',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='SchoolName',
            new_name='schoolName',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='UserId',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Yourhobby',
            new_name='yourhobby',
        ),
        migrations.RenameField(
            model_name='projectviews',
            old_name='ProjectId',
            new_name='projectId',
        ),
        migrations.RenameField(
            model_name='projectviews',
            old_name='UserId',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='projectviews',
            old_name='Views',
            new_name='views',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='Ammount',
            new_name='ammount',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='PaymentStatus',
            new_name='paymentStatus',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='Reason',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='RefundDate',
            new_name='refundDate',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='Refund_requestDate',
            new_name='refund_requestDate',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='Transactionid',
            new_name='transactionid',
        ),
        migrations.RenameField(
            model_name='refund',
            old_name='Userid',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='UserId',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='solutiondesk',
            old_name='InstructedBy',
            new_name='instructedBy',
        ),
        migrations.RenameField(
            model_name='solutiondesk',
            old_name='Solution',
            new_name='solution',
        ),
        migrations.RenameField(
            model_name='solutiondesk',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='userprojects',
            old_name='Demo_img',
            new_name='demo_img',
        ),
        migrations.RenameField(
            model_name='userprojects',
            old_name='Files',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='userprojects',
            old_name='Projectabout',
            new_name='projectabout',
        ),
        migrations.RenameField(
            model_name='userprojects',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='userprojects',
            old_name='UserId',
            new_name='userId',
        ),
        migrations.RemoveField(
            model_name='advanced',
            name='Benifits',
        ),
        migrations.RemoveField(
            model_name='advanced',
            name='CoursesId',
        ),
        migrations.RemoveField(
            model_name='advanced',
            name='Prerequisites',
        ),
        migrations.RemoveField(
            model_name='batchtype',
            name='CoursesId',
        ),
        migrations.RemoveField(
            model_name='beginner',
            name='Benifits',
        ),
        migrations.RemoveField(
            model_name='beginner',
            name='Prerequisites',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='CoursesId',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='CourseName',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='Current_Demandofcourse',
        ),
        migrations.RemoveField(
            model_name='helpdesk',
            name='CoursesId',
        ),
        migrations.RemoveField(
            model_name='helpdesk',
            name='Paymentid',
        ),
        migrations.RemoveField(
            model_name='intermediate',
            name='Benifits',
        ),
        migrations.RemoveField(
            model_name='intermediate',
            name='Prerequisites',
        ),
        migrations.RemoveField(
            model_name='solutiondesk',
            name='QueryId',
        ),
        migrations.AddField(
            model_name='advanced',
            name='benifits',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advanced',
            name='coursesId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advanced',
            name='prerequisites',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchtype',
            name='coursesId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beginner',
            name='benifits',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beginner',
            name='prerequisites',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certification',
            name='coursesId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='course_Aim',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='current_Demandofcourse',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='coursesId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='paymentid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intermediate',
            name='benifits',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intermediate',
            name='prerequisites',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solutiondesk',
            name='queryId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Helpdesk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beginner',
            name='coursesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
        migrations.AlterField(
            model_name='intermediate',
            name='coursesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='coursesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='coursesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
        migrations.AddField(
            model_name='course_details',
            name='coursesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
        migrations.AddField(
            model_name='course_details',
            name='trainerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class_review',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Trainer_course'),
        ),
        migrations.AddField(
            model_name='class_attendance',
            name='coursesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
        migrations.AddField(
            model_name='class_attendance',
            name='trainerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class_activity',
            name='coursesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
        migrations.AddField(
            model_name='class_activity',
            name='trainerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
