# Generated by Django 3.0.8 on 2020-12-01 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20201031_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.RemoveField(
            model_name='class_attendance',
            name='coursesId',
        ),
        migrations.RemoveField(
            model_name='class_attendance',
            name='trainerId',
        ),
        migrations.RemoveField(
            model_name='class_review',
            name='classid',
        ),
        migrations.RemoveField(
            model_name='course_details',
            name='coursesId',
        ),
        migrations.RemoveField(
            model_name='course_details',
            name='trainerId',
        ),
        migrations.RemoveField(
            model_name='trainer_attendance',
            name='trainerId',
        ),
        migrations.RemoveField(
            model_name='trainer_course',
            name='coaching_courseid',
        ),
        migrations.RemoveField(
            model_name='trainer_profile',
            name='trainerId',
        ),
        migrations.AlterField(
            model_name='batchtype',
            name='coursesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='coursesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
        migrations.AlterField(
            model_name='course_info',
            name='coursesId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
        migrations.AlterField(
            model_name='democlass',
            name='coursesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
        migrations.AlterField(
            model_name='democlass_otp',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 9, 33, 35, 722925, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='helpdesk',
            name='coursesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='coursesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='coursesId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Courses'),
        ),
        migrations.AlterField(
            model_name='solutiondesk',
            name='queryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Helpdesk'),
        ),
        migrations.DeleteModel(
            name='Class_activity',
        ),
        migrations.DeleteModel(
            name='Class_attendance',
        ),
        migrations.DeleteModel(
            name='Class_Review',
        ),
        migrations.DeleteModel(
            name='Course_details',
        ),
        migrations.DeleteModel(
            name='Trainer_attendance',
        ),
        migrations.DeleteModel(
            name='Trainer_course',
        ),
        migrations.DeleteModel(
            name='Trainer_profile',
        ),
    ]
